[package]
name = "fast-hashdeep"
version = "0.1.0"
authors = ["Peter Law <PeterJCLaw@gmail.com>"]

[dependencies]
chrono = "^0.4"
clap = { version = "^3.0", features = ["derive"] }
itertools = "^0.10"
md5 = "^0.7"
walkdir = "^2"
