#!/bin/sh

find tests -type f -print0 | xargs -0 touch --date='2018-01-29 20:01:02.012034'

if [ -z "$@" ]
then
    IMPLEMENTATION=./fast-hashdeep.py
else
    IMPLEMENTATION="$@"
fi

DIFF=$(which colordiff || which diff)

result=0
for d in all-changes move-only unchanged
do
    echo "Testing $d"
    $IMPLEMENTATION audit tests/$d tests/$d.record > tests/audit-$d.output
    $DIFF -u tests/audit-$d.expected tests/audit-$d.output
    result=$((result | $?))
done

exit $result
